<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NetArchTest.Rules" />
    <ProjectReference Include="../../src/GovErp.Domain.Shared/GovErp.Domain.Shared.csproj" />
    <ProjectReference Include="../../src/GovErp.Domain.Validation/GovErp.Domain.Validation.csproj" />
    <ProjectReference Include="../../src/GovErp.Domain.Payables/GovErp.Domain.Payables.csproj" />
    <ProjectReference Include="../../src/GovErp.Application.Web/GovErp.Application.Web.csproj" />
    <ProjectReference Include="../../src/GovErp.Infrastructure/GovErp.Infrastructure.csproj" />
    <ProjectReference Include="../../src/GovErp.Web/GovErp.Web.csproj" />
    <ProjectReference Include="../../src/GovErp.Domain.ChartOfAccounts/GovErp.Domain.ChartOfAccounts.csproj" />
    <ProjectReference Include="../../src/GovErp.Domain.Ledger/GovErp.Domain.Ledger.csproj" />
  </ItemGroup>
</Project>
